### ISSUE TITLE
C/C++ support

### ISSUE THREAD

**Issue by innerout** [emacs-lsp/lsp-sonarlint#12]
Hi, thanks for the great plugin! Sonarlint has support for C/C++, but the plugin does not support it yet.
Would it be difficult to provide this kind of support?

**Comment by Sasanidas** [comment]
Sorry about the response, delay, the last time that I checked the back-end for C/C++, it was in the paid version.

If you can post the link to download the java back-end file, I can add it without problems :+1:

**Comment by innerout** [comment]
I did not know it was a paid feature.

**Comment by f-michaut** [comment]
It looks like the plugin for VisualStudio is open source, and the README talks about C++: https://github.com/SonarSource/sonarlint-visualstudio

I would also love to have C++ support for this plugin !

**Comment by Sasanidas** [comment]
I only added some languages that were in https://binaries.sonarsource.com/?prefix=Distribution/ , which as far as I know, are open source.
There is also another list in  https://binaries.sonarsource.com/?prefix=CommercialDistribution/ , but I think you have to pay for those (or are propietary). So I didn't implement those.

In any case, you are free to experiment and add support for more languages, go would be a nice addition.

**Comment by thahnen** [comment]
For C/C++ analysis, please see #21 regarding the analyzer for it.

**Comment by Horrih** [comment]
For those stumbling on this issue, two PRs implement cfamily support, see #22 #20

**Comment by Sasanidas** [comment]
Merged! https://github.com/emacs-lsp/lsp-sonarlint/pull/22
