### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by ZelCloud** [emacs-lsp/lsp-sonarlint#7]
Looking through the languages folder typescript doesn't seem to be included so the following fails

```elisp
 (require 'lsp-sonarlint-typescript)
 (setq lsp-sonarlint-typescript-enabled t)
```

but in the static analysis rules portion of the readme typescript rules are included out of the box, so would it be possible to add typescript support?

**Comment by Sasanidas** [comment]
Hello @ZelCloud , yes you are right, my bad, I wrongly thought that the JavaScript plug-in also works with typescript.

It should be quite easy, create a new folder, add the .el file to it with the same name as the server (in this case, typescript) and add the major mode to the variable `lsp-sonarlint-modes-enabled`. It is probably similar to the javascript one.

I don't have too much time right now, but it shouldn't  take too long, if you willing to create a pull request, I will review it and merge it.

Regards

**Comment by Sasanidas** [comment]
I think I can close this issue, solve by the last merge request https://github.com/emacs-lsp/lsp-sonarlint/pull/8 :+1:

**Comment by goshatch** [comment]
Hi @Sasanidas, it would be nice to cut a new release including the Typescript support!
